name: Mise à jour quotidienne des portefeuilles

on:
  schedule:
    - cron: '0 20 * * *'  # Tous les jours à 20h UTC (21h ou 22h France selon heure d'été)
  workflow_dispatch:      # Permet de lancer manuellement

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas yfinance numpy requests

      - name: Run update script
        run: python scripts/update_portfolios.py

      - name: Commit & push si changements
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour quotidienne des portefeuilles $(date +%Y-%m-%d)"
          git push
